### ISSUE TITLE
the trait `rolodex::tower::Service<_>` is not implemented for `rolodex::Dst`

### ISSUE THREAD

**Issue by brndnmtthws** [tower-rs/tower-grpc#159]
I'm still a rust noob, so please forgive me, but I've got a compile error that I can't decipher:

```
error[E0277]: the trait bound `rolodex::Dst: rolodex::tower::Service<_>` is not satisfied
  --> src/rolodex.rs:26:27
   |
26 |     let mut make_client = client::Connect::new(Dst, h2_settings, DefaultExecutor::current());
   |                           ^^^^^^^^^^^^^^^^^^^^ the trait `rolodex::tower::Service<_>` is not implemented for `rolodex::Dst`
   |
   = note: required because of the requirements on the impl of `rolodex::tower_util::MakeConnection<_>` for `rolodex::Dst`
```

The code is pretty much a direct copy/paste of the helloworld client:

```rust
extern crate rolodex_grpc;
extern crate futures;
extern crate tokio;
extern crate tower_grpc;
extern crate tower_h2;
extern crate tower_request_modifier;
extern crate tower_service;
extern crate tower_util;
extern crate tower;

use futures::{Future, Poll};
use tokio::executor::DefaultExecutor;
use std::net::SocketAddr;
use tokio::net::tcp::{ConnectFuture, TcpStream};
use tower_grpc::Request;
use tower_h2::client;
use tower_service::Service;
use tower_util::MakeService;
use rolodex_grpc::proto;

fn run() {
    let uri: http::Uri = format!("http://[::1]:50051").parse().unwrap();

    let h2_settings = Default::default();
    let addr = "[::1]:8888".parse().unwrap();
    let mut make_client = client::Connect::new(Dst, h2_settings, DefaultExecutor::current());

    let say_hello = make_client
        .make_service(())
        .map(move |conn| {
            use rolodex_grpc::proto::client::Rolodex;

            let conn = tower_request_modifier::Builder::new()
                .set_origin(uri)
                .build(conn)
                .unwrap();

            Rolodex::new(conn)
        })
        .and_then(|mut client| {
            use rolodex_grpc::proto::NewUser;

            client
                .add_user(Request::new(NewUser {
                    name: "What is in a name?".to_string(),
                }))
                .map_err(|e| panic!("gRPC request failed; err={:?}", e))
        })
        .and_then(|response| {
            error!("RESPONSE = {:?}", response);
            Ok(())
        })
        .map_err(|e| {
            error!("ERR = {:?}", e);
        });

    tokio::run(say_hello);
}

struct Dst;

impl Service<()> for Dst {
    type Response = TcpStream;
    type Error = ::std::io::Error;
    type Future = ConnectFuture;

    fn poll_ready(&mut self) -> Poll<(), Self::Error> {
        Ok(().into())
    }

    fn call(&mut self, _: ()) -> Self::Future {
        let addr = "[::1]:50051".parse().unwrap();
        TcpStream::connect(&addr)
    }
}
```

Thoughts?

**Comment by LucioFranco** [comment]
@brndnmtthws what version of tower_service do you have locally?

**Comment by brndnmtthws** [comment]
From `Cargo.lock`:

```toml
[[package]]
 name = "tower-service"
 version = "0.2.0"
 source = "git+https://github.com/tower-rs/tower#979c1399127bdb269c751b99c12b3adfad55463c"
 dependencies = [
  "futures 0.1.26 (registry+https://github.com/rust-lang/crates.io-index)",
 ]
```

I'll try reverting to an older version to see if that helps.

**Comment by seanmonstar** [comment]
Check if you're depending on `tower-service` specifically from git. tower-grpc depends on the crates.io 0.2 version, so if you implement the git one, rust thinks of them as completely different traits.

**Comment by brndnmtthws** [comment]
This is how `Cargo.toml` looks:

```toml
tower = { git = "https://github.com/tower-rs/tower" }
tower-buffer = { git = "https://github.com/tower-rs/tower" }
tower-grpc = { git = "https://github.com/tower-rs/tower-grpc" }
tower-h2 = { git = "https://github.com/tower-rs/tower-h2" }
tower-http = { git = "https://github.com/tower-rs/tower-http" }
tower-request-modifier = { git = "https://github.com/tower-rs/tower-http" }
tower-service = { git = "https://github.com/tower-rs/tower" }
tower-util = { git = "https://github.com/tower-rs/tower" }
```

So you're saying I should just do `tower-service = "0.2"` instead?
